services:
  postgres:
    image: postgres:16-alpine
    container_name: data_processing_be_db
    environment:
      - POSTGRES_USER=tuananh
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=data_processing_be
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tuananh -d data_processing_be"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  backend:
#    image: data_processing_be
#    container_name: data_processing_be
#    ports:
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    restart: unless-stopped

volumes:
  pg_data: