name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/deploy.yml"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - run: docker compose up -d
      - name: Wait for postgres to be healthy
        run: |
          for i in {1..20}; do
            docker compose exec -T postgres pg_isready -U tuananh -d data_processing_be && break
            echo "Waiting for postgres... ($i)"
            sleep 3
          done
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - run: chmod +x gradlew
      - name: Build project
        run: ./gradlew test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/data_processing_be
          SPRING_DATASOURCE_USERNAME: tuananh
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: 300000

  push-ghcr:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tanh8805/data_processing_ai-agent:latest
            ghcr.io/tanh8805/data_processing_ai-agent:v${{github.run_number}}